# Generated by Django 4.2.6 on 2023-11-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
        ('solicitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basemodel',
                'verbose_name_plural': 'basemodels',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='EncargadoBaseMisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=10, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('codigo', models.CharField(max_length=9, unique=True, verbose_name='Codigo')),
                ('serial', models.CharField(max_length=9, unique=True, verbose_name='Serial')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
                'db_table': 'Encargados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuenteAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('laguna', 'Laguna'), ('rio', 'Rio'), ('manantial', 'Manantial'), ('quebrada', 'Quebrada'), ('morichal', 'Morichal')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material_vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('bahareque', 'Bahareque'), ('bloque', 'Bloque'), ('zinc', 'Zinc'), ('otros', 'Otros')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionDrenaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('canales', 'Canales'), ('superficial', 'Superficial'), ('natural', 'Natural'), ('zanja', 'Zanja')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesAguaBlancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pozo', 'Pozo'), ('jaguey', 'Jagüey'), ('acueducto', 'Acueducto'), ('cisterna', 'Cisterna'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesAguasServidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pozo_septico', 'Pozo séptico'), ('cloacas', 'Cloacas'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesElectricidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('planta', 'Planta Eléctrica'), ('generador', 'Generador Eléctrico'), ('tendido', 'Tendido Eléctrico')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('directo', 'Directo'), ('bombona', 'Bombona'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('fijo', 'Fijo'), ('movil', 'Móvil'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pickup', 'Pick Up'), ('350', '350'), ('750', '750'), ('gandola', 'Gandola'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('goteo', 'Goteo'), ('gravedad', 'Gravedad'), ('microaspersión', 'Microaspersión'), ('aspersión', 'Aspersión'), ('pivote', 'Pivote')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocacionTierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('agricola', 'Agrícola'), ('pecuario', 'Pecuario'), ('forestal', 'Forestal'), ('acuicola', 'Acuícola'), ('mineria', 'Minería'), ('turismo', 'Turismo'), ('otros', 'Otros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.basemodel')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descipcion', models.CharField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria_Solicitud',
            },
            bases=('solicitud.basemodel',),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona_atendio', models.CharField(max_length=50)),
                ('cedula', models.CharField(blank=True, max_length=9)),
                ('tlf', models.CharField(blank=True, max_length=11)),
                ('fecha_visita', models.DateField()),
                ('fecha_proxima_visita', models.DateField()),
                ('motivo_visita', models.CharField(choices=[('urgente', 'Urgente'), ('rutina', 'Rutina')], max_length=10)),
                ('lote1', models.CharField(blank=True, max_length=5, null=True)),
                ('lote2', models.CharField(blank=True, max_length=5, null=True)),
                ('lote3', models.CharField(blank=True, max_length=5, null=True)),
                ('lote4', models.CharField(blank=True, max_length=5, null=True)),
                ('edad_cultivo', models.CharField(max_length=9)),
                ('superficie_up', models.FloatField()),
                ('superficie_preparada', models.FloatField(blank=True, max_length=10)),
                ('superficie_sembrada', models.FloatField(blank=True, max_length=10)),
                ('rubro_sembrado', models.CharField(max_length=20)),
                ('semilla_variedad', models.CharField(max_length=20)),
                ('realizar_recomendacion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('fecha_estimada_cosecha', models.DateField()),
                ('superficie_por_consechar', models.FloatField(blank=True, max_length=10)),
                ('superficie_cosechada', models.FloatField(blank=True, max_length=10)),
                ('superficie_perdida', models.FloatField(blank=True, max_length=10)),
                ('superficie_efectiva', models.FloatField(blank=True, max_length=10)),
                ('estimacion_del_redimiento', models.CharField(max_length=20)),
                ('redimiento', models.CharField(max_length=20)),
                ('redimiento_total', models.CharField(max_length=20)),
                ('dar_continuidad', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('coordenadas_norte', models.CharField(max_length=10)),
                ('coordenadas_sur', models.CharField(max_length=10)),
                ('Sembrador_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sembradores')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_tecnico', to='User.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=50)),
                ('direccion_unidad', models.CharField(max_length=100)),
                ('como_llegar', models.TextField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('vive_en_unidad', models.BooleanField(default=False)),
                ('frecuencia_visita', models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='diario', max_length=10, null=True)),
                ('tenencia_de_tierra', models.CharField(blank=True, choices=[('init', 'Init'), ('blandia', 'Blandia'), ('propia', 'Propia'), ('ejido', 'Ejido'), ('zona_protegida', 'Zona Protegida PERMITIDA'), ('otros', 'Otros')], max_length=50)),
                ('vivienda', models.BooleanField(default=False)),
                ('electricidad', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='si', max_length=3)),
                ('transporte_insumo', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='si', max_length=3)),
                ('telefono', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=3)),
                ('gas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=3)),
                ('aguas_blancas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=3)),
                ('aguas_servidas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=3)),
                ('superficie_total_up', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Total de la UP (ha)')),
                ('superficie_aprovechable_up', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Aprovechable de la UP (ha)')),
                ('superficie_gps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Medida con GPS (ha)')),
                ('condiciones_drenaje', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=20, null=True)),
                ('condiciones_sistema_riego', models.CharField(blank=True, choices=[('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=20, null=True)),
                ('superficie_externa', models.CharField(blank=True, choices=[('asfaltada', 'Asfaltada'), ('engrasonada', 'Engrasonada'), ('tierra y grazon', 'Tierra y Grazon'), ('fluvial', 'Fluvial'), ('ripio', 'Ripio'), ('otros', 'Otros')], max_length=20, null=True)),
                ('superficie_interna', models.CharField(blank=True, choices=[('asfaltada', 'Asfaltada'), ('engrasonada', 'Engrasonada'), ('tierra y grazon', 'Tierra y Grazon'), ('fluvial', 'Fluvial'), ('ripio', 'Ripio'), ('otros', 'Otros')], max_length=20, null=True)),
                ('Sembrador_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.sembradores')),
                ('drenaje_opciones', models.ManyToManyField(blank=True, to='solicitud.opciondrenaje')),
                ('fuentes_agua', models.ManyToManyField(blank=True, to='solicitud.fuenteagua')),
                ('material_vivienda', models.ManyToManyField(to='solicitud.material_vivienda')),
                ('opciones_aguas_blancas', models.ManyToManyField(blank=True, to='solicitud.opcionesaguablancas')),
                ('opciones_aguas_servidas', models.ManyToManyField(blank=True, to='solicitud.opcionesaguasservidas')),
                ('opciones_electricidad', models.ManyToManyField(blank=True, to='solicitud.opcioneselectricidad')),
                ('opciones_gas', models.ManyToManyField(blank=True, to='solicitud.opcionesgas')),
                ('opciones_telefono', models.ManyToManyField(blank=True, to='solicitud.opcionestelefono')),
                ('opciones_transporte', models.ManyToManyField(blank=True, to='solicitud.opcionestransporte')),
                ('sistema_riego', models.ManyToManyField(blank=True, to='solicitud.sistemariego')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tecnico')),
                ('vocacion_tierra', models.ManyToManyField(blank=True, to='solicitud.vocaciontierra')),
            ],
            options={
                'db_table': 'Inspecciones',
            },
        ),
        migrations.CreateModel(
            name='BaseGrandesMisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre de la Finca')),
                ('municipio', models.CharField(choices=[('Agua Blanca', 'AGUA BLANCA'), ('ARAURE', 'ARAURE'), ('ESTELLER', 'ESTELLER'), ('GUANARE', 'GUANARE'), ('GUANARITO', 'GUANARITO'), ('JOSÉ VICENTE DE UNDA', 'JOSÉ VICENTE DE UNDA'), ('OSPINO', 'OSPINO'), ('PAPELÓN', 'PAPELÓN'), ('SAN GENARO DE BOCONOÍTO', 'SAN GENARO DE BOCONOÍTO'), ('SAN RAFAEL DE ONOTO', 'SAN RAFAEL DE ONOTO'), ('SANTA ROSALÍA', 'SANTA ROSALÍA'), ('SUCRE', 'SUCRE'), ('TURÉN', 'TURÉN')], default='GUANARE', max_length=100, verbose_name='Municipios')),
                ('nombre_p', models.CharField(max_length=50, verbose_name='Parroquia')),
                ('nombre_c', models.CharField(max_length=50, verbose_name='Comunidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.encargadobasemisiones', verbose_name='Encargado o Responsable')),
            ],
            options={
                'verbose_name': 'Fincas_para_produccion',
                'verbose_name_plural': 'Fincas_para_produccion',
                'db_table': 'Fincas_para_produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(blank=True, choices=[('APROBADA', 'APROBADA'), ('ESPERA', 'ESPERA')], default='ESPERA', max_length=9, null=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('descripcion_motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante', verbose_name='Solicitante')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.categorias', verbose_name='Categoria')),
            ],
        ),
    ]
