# Generated by Django 4.0.4 on 2022-05-25 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descipcion', models.CharField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria_Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('estatus', models.CharField(choices=[('ENTREGADA', 'Entregada'), ('ESPERA', 'Espera'), ('RECHAZADA', 'Rechazada')], default='ESPERA', max_length=9)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.categorias', verbose_name='id Categoria')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante', verbose_name='id Solicitante')),
            ],
        ),
    ]
