# Generated by Django 4.0.4 on 2022-05-25 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Comunas')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Municipios')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Parroquias')),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.municipio')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('estatus', models.BooleanField(default=False)),
                ('cedula', models.CharField(max_length=25, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.comuna')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.municipio')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.parroquia')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'Solicitantes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.parroquia'),
        ),
    ]
