# Generated by Django 4.2.6 on 2023-11-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sembradores',
            name='user',
        ),
    ]
