# Generated by Django 4.2.6 on 2023-11-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_sembradores_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sembradores',
            old_name='apellido2',
            new_name='conyuge_apellido',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='cedula2',
            new_name='conyuge_cedula',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='edad2',
            new_name='conyuge_edad',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='caserio3',
            new_name='conyuge_nombre',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='sexo2',
            new_name='conyuge_sexo',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='telefono_celular2',
            new_name='conyuge_telefono_celular',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='telefono_fijo2',
            new_name='conyuge_telefono_fijo',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='ciudad_cercana3',
            new_name='direccion_habitacion_caserio',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='estado3',
            new_name='direccion_habitacion_ciudad_cercana',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='direccion_habitacion3',
            new_name='direccion_habitacion_direccion',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='municipio3',
            new_name='direccion_habitacion_estado',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='nombre2',
            new_name='direccion_habitacion_municipio',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='parroquia3',
            new_name='direccion_habitacion_parroquia',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='punto_referencia3',
            new_name='direccion_habitacion_punto_referencia',
        ),
        migrations.RenameField(
            model_name='sembradores',
            old_name='sector3',
            new_name='direccion_habitacion_sector',
        ),
    ]
