# Generated by Django 4.2.6 on 2023-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_apellido2_sembradores_conyuge_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sembradores',
            options={'verbose_name': 'Sembrador', 'verbose_name_plural': 'Sembradores'},
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='cedula_agraria',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula Agraria'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='codigo_asonaproyuca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Asonaproyuca'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True, verbose_name='Sexo del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_telefono_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Celular del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='conyuge_telefono_fijo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo del Cónyuge'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_caserio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caserío de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_ciudad_cercana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad Cercana de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_municipio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_parroquia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parroquia de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_punto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Punto de Referencia de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='direccion_habitacion_sector',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sector de la Dirección de Habitación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)')], max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Google Maps'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='logue_complete',
            field=models.BooleanField(default=False, verbose_name='Registro Completo'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='nombre_unidad',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Unidad'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='parroquia',
            field=models.CharField(max_length=50, verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='profesion_ocupacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Profesión u Ocupación'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Casa'),
        ),
        migrations.AlterField(
            model_name='sembradores',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Personal'),
        ),
        migrations.AlterModelTable(
            name='sembradores',
            table=None,
        ),
    ]
