# Generated by Django 4.2.6 on 2023-11-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_sembradores_options_alter_sembradores_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sembradores',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
